fix: Update content item's cover image to be parent's if null
ApollosProject/apollos-shovel pull request #10
Opened 2021-06-30 15:18 UTC by tomthornton

Fancy SQL query from @vinnyjth

2021-06-30 15:35 UTC, vinnyjth requested changes
Getting close! Nice work @tomthornton

2021-06-30 15:35 UTC, vinnyjth commented on dags/rock_cover_image.py
> +            imageId = squareImages[0]['Guid']
So - one thing I ran into earlier is that `Guid` is the same for every attribute of the same type. So every content item of the same type has the same image attribute, but the values of those attributes change. 

For that reason - as you can see from the div, I ended up making a new originId by combining the `attribute.id` and the `content_item.id` 
`str(content_item['Id']) + "/" + str(attribute[id])`

We'll need to do that here - or at least do it on line 29

2021-06-30 15:35 UTC, vinnyjth commented on dags/rock_cover_image.py
> +            return attribute['FieldTypeId'] == 10 or ('image' in attributeKey.lower() and isinstance(attributeValue, str) and attributeValue.startswith('http'))
We need to revert this change :) this is to help prevent returning values without an image.

2021-06-30 15:35 UTC, vinnyjth commented on dags/rock_cover_image.py
> +        return pg_hook.get_first('SELECT id FROM "media" WHERE "originId" = %s', (imageId,))[0]
awesome change here. returning the actual postgres ID certainly makes this logic easier to follow.

2021-06-30 15:35 UTC, vinnyjth commented on dags/rock_cover_image.py
> +        coverImageId = get_best_image_id(imageAttributes, pg_hook)
if you change where `get_best_image_id` is defined, you can avoid passing `pg_hook` :D

2021-06-30 15:35 UTC, vinnyjth commented on dags/rock_cover_image.py
> +        pg_hook.run(
sweet!

2021-06-30 15:35 UTC, vinnyjth commented on dags/rock_cover_image.py
>          if(coverImageId):
one more scenario I thought of :) if the `coverImageId` becomes `None`, we should handle that and `unset` the `coverImageId` (if an admin deletes an image off a content item, for example)

2021-06-30 15:35 UTC, vinnyjth commented on dags/rock_cover_image.py
>          if(coverImageId):
I can make a separate note for this in basecamp, we can keep this PR focused.

2021-06-30 19:03 UTC, vinnyjth commented on dags/rock_cover_image.py
> +            imageId = squareImages[0]['Guid']
@tomthornton Take a look at this comment, I think we still need to switch over to the compound `Content`/`Attribute` ID

2021-07-06 13:57 UTC, tomthornton commented
@vinnyjth updated the ID ^^ This should be good to go.

2021-07-06 14:32 UTC, tomthornton commented
@vinnyjth good catch ^^ still getting used to this new id format for media

2021-07-06 17:00 UTC, tomthornton reviewed
Got it. Content Item Id is first

2021-07-06 17:01 UTC, vinnyjth commented
> Gotcha. Does this mean we will need to update the media shovel to reflect this?

it was actually, but it looks like we accidentally overwrote the change in a recent PR. That's my bad for not catching it. I reverted it as a commit in this PR. 

https://github.com/ApollosProject/apollos-shovel/pull/10/commits/47b92a48251f483083de5e46d26534e0df5edf01

2021-07-06 17:04 UTC, vinnyjth reviewed
I tested the PR locally and ran into a few issues, but they should be easy fixes! I think we just need to settle on `get_best_image_id` returning a media.id or a `media.originId`, and reacting accordingly in `update_content_item_cover_image`

2021-07-06 17:04 UTC, vinnyjth commented on dags/rock_cover_image.py
> +                    return images[0]['Id']
I think this early return here is causing problems. When running the dag locally I'm getting conflicting `IDs` since this ID isn't being turned into a media ID.

2021-07-06 17:04 UTC, vinnyjth commented on dags/rock_cover_image.py
> +                return pg_hook.get_first('SELECT id FROM "media" WHERE "originId" = %s', (concatImageId))[0]
Related to my comment above, what if we returned the `originId` here and kept the above code?

2021-07-07 15:23 UTC, tomthornton commented
@vinnyjth` I think the problem was that `return pg_hook.get_first('SELECT id FROM "media" WHERE "originId" = %s', (concatImageId,))[0]` was missing that comma after `concatImageId`. This is working for me now.

2021-07-07 15:24 UTC, vinnyjth commented
> @vinnyjth I think the problem was that `return pg_hook.get_first('SELECT id FROM "media" WHERE "originId" = %s', (concatImageId,))[0]` was missing that comma after `concatImageId`. This is working for me now.

My bad for removing that, are you ready for me to review this again?

2021-07-07 15:39 UTC, tomthornton commented
@vinnyjth yep!

2021-07-07 18:22 UTC, vinnyjth commented
@tomthornton Something still must be off :/ 

Here are the steps I took, and here is what I'm seeing.

1. Truncated my media table with cascade locally
2. Truncated my contentItems table with cascade locally. 
3. Re-ran the backfill dag and confirmed that there were no errors. 

Here's what I'm seeing in my contentItems table. 
![image](https://user-images.githubusercontent.com/1637694/124808990-9ae2a880-df2d-11eb-971f-9b4dd02c9b77.png)

and in my media table

![image](https://user-images.githubusercontent.com/1637694/124809180-d4b3af00-df2d-11eb-8fb2-258b8546b5f6.png)

From what I can tell, looking at the code, I believe you're `concating` the wrong media image id in the `update_content_item_cover_image` method. Looking at the logs of the `dag` I'm seeing what looks like a combination of a media `postgres` ID and a media `originId`

```
[2021-07-07 18:11:44,481] {dbapi.py:180} INFO - Running statement: UPDATE "contentItems" SET "coverImageId" = (SELECT id FROM "media" WHERE "originId" = %s) WHERE "originId"::Integer = %s, parameters: ('21/e5994c27-2de9-4261-81f3-e02c65f5674f', 21)
[2021-07-07 18:11:44,484] {dbapi.py:186} INFO - Rows affected: 1
```

I think there's two things you can do to resolve this - 

1. Stop querying for the `postgresId` in the `get_best_cover_image` method and pass the originId to the `update_content_item_cover_image`, eliminating the need for the pg query inside `get_best_cover_image`

2. You are passing the `media.id` to the `update_content_item_cover_image` method, so you should be able to eliminate the subquery instead of your sql and use the `media.id` directly.

2021-07-07 19:58 UTC, tomthornton commented
@vinnyjth that's my bad. I had tested it yesterday and it was working... but I don't know why it did. I ran this and it worked for most of the content items but it didn't update based on the parent content item with that SQL query you wrote.

2021-07-08 11:32 UTC, vinnyjth approved these changes
Looking good! Nice work landing the plane

2021-07-08 11:32 UTC, vinnyjth commented on dags/rock_cover_image.py
> +                return pg_hook.get_first('SELECT id FROM "media" WHERE "originId" = %s', (concatImageId,))[0]
is there any reason you decided to keep this query?

2021-07-08 13:34 UTC, tomthornton commented on dags/rock_cover_image.py
> +                return pg_hook.get_first('SELECT id FROM "media" WHERE "originId" = %s', (concatImageId,))[0]
Don't we still need the postgres media id? I guess we could do this in the update query... I may shift it over once we get to the next part which is setting the cover image as null if it's deleted

2021-07-08 13:53 UTC, vinnyjth commented on dags/rock_cover_image.py
> +                return pg_hook.get_first('SELECT id FROM "media" WHERE "originId" = %s', (concatImageId,))[0]
It's either fetch the media id here, or use the `originId` in the  `update_content_item_cover_image` via a subquery. A bit more efficient since it takes us down to one query per insert, but not a huge deal :) Was curious if you had spotted something I missed.

2021-07-08 13:53 UTC, merged