Crossroads Kids' Club Data
ApollosProject/apollos-shovel pull request #112
Opened 2022-01-07 12:43 UTC by liamillard

### About

This PR adds shovel capability for crossroads kids club data coming from Contentful.

### Testing

### Screenshots

2022-01-11 15:28 UTC, vinnyjth commented on README.md
> +# Apollos Shovel
💥 

can you guys come use some of our tech everyday?

2022-01-11 16:45 UTC, liamillard commented on README.md
> +# Apollos Shovel
I'm a firm believer in the idea that if you're using something for the first time, you're updating the readme 🙂

2022-01-11 19:24 UTC, liamillard commented
This is finally ready for review @vinnyjth! If there are a lot of things wrong with it I'm happy to pair rather than make you write out a million github comments 😅

2022-01-13 16:52 UTC, vinnyjth commented on dags/contentful_crossroads/cr_contentful_content_items.py
> +            "apollos_type": "Media",
```suggestion
            "apollos_type": "ContentItem",
```

2022-01-13 16:57 UTC, vinnyjth requested changes
One teeny thing change and then we are good to Lia!

2022-01-13 16:57 UTC, vinnyjth commented on dags/contentful_crossroads/cr_contentful_content_items.py
> +            "apollos_type": "Media",
```suggestion
            "apollos_type": "MediaContentItem",
```

2022-01-13 16:57 UTC, vinnyjth commented on dags/contentful_crossroads/cr_contentful_content_items.py
> +        video_url = "https://player.vimeo.com/external/522397154.m3u8?s=288eb6e0d740e0b2344b7d003b59f1b4245dfde3"
We have some vimeo api code hiding somewhere :D

2022-01-13 18:51 UTC, merged