Start of feature operator
ApollosProject/apollos-shovel pull request #20
Opened 2021-07-07 01:55 UTC by vinnyjth

2021-07-07 16:21 UTC, vinnyjth commented
<img width="2843" alt="Screen Shot 2021-07-07 at 12 19 54 PM" src="https://user-images.githubusercontent.com/1637694/124795278-dbd2c100-df1d-11eb-8c0d-6e9f7bcb0301.png">

2021-07-07 18:27 UTC, vinnyjth commented on dags/rock-content-item-backfill-core-dag.py
> +    base_items = PythonOperator(
I renamed the operators with actually helpful names, they were getting hard to manage :)

2021-07-08 13:49 UTC, tomthornton requested changes
Getting all of the features imported but the apollos ID isn't updating because there doesn't seem to be an `originType` column on the features table

2021-07-08 13:49 UTC, tomthornton commented on dags/rock_features.py
> +        add_apollos_ids = """
It appears that "originType" is not a column on the features table. Are there more recent migrations that adds this?

2021-07-08 13:54 UTC, vinnyjth commented on dags/rock_features.py
> +        add_apollos_ids = """
Good catch! That's a miss on my part.

2021-07-08 13:55 UTC, vinnyjth commented
@tomthornton Updated to accommodate that this table doesn't have/need an originId.

2021-07-09 15:52 UTC, tomthornton approved these changes
Great looks good!

2021-07-09 15:52 UTC, merged