feat: Rock Persona -> Person operator
ApollosProject/apollos-shovel pull request #22
Opened 2021-07-08 18:11 UTC by vinnyjth

2021-07-08 18:12 UTC, vinnyjth commented
![image](https://user-images.githubusercontent.com/1637694/124970883-7ef70980-dff6-11eb-8a62-62b8fadc9e2e.png)

2021-07-09 16:26 UTC, tomthornton requested changes
Awesome! Worked for me. Just need to fix the merge conflicts

2021-07-09 17:56 UTC, vinnyjth commented
@tomthornton thanks! merge conflicts fixed

2021-07-09 17:58 UTC, tomthornton approved these changes
Great!

2021-07-09 17:59 UTC, merged