chore: Add channel cover image dag
ApollosProject/apollos-shovel pull request #49
Opened 2021-08-11 22:21 UTC by tomthornton

2021-08-11 23:34 UTC, redreceipt commented
@tomthornton @vinnyjth this seems overkill to me, we just want the channel image to be the fallback content item in the event there is no other. seems like that could be done entirely inside the cover image class https://github.com/ApollosProject/apollos-shovel/blob/master/dags/rock/rock_cover_image.py

we don't necessarily care about rock channels other than mapping them to categories. take my opinion with a grain of salt though, I don't know any DB schema arch strategies you guys have built thus far.

2021-08-12 00:31 UTC, redreceipt commented on dags/rock/rock_channel_image.py
> +                lambda channel: safeget(channel, "AttributeValues", "BlogImage"),
`BlogImage` is naive for all churches, we should use the regular content image utility functions to find the images -  "if `image` in the attribute name" etc...

2021-08-12 00:37 UTC, redreceipt commented
...all that being said, if we deem this is correct code and could be simply be improved, could we run the shovel against their production instance using this PR just to get images in the DB, and then we can talk about finishing the PR? I just wanna get their app looking good since they wanna launch Sunday.

2021-08-12 13:28 UTC, vinnyjth commented on dags/rock/rock_channel_image.py
> +                lambda channel: safeget(channel, "AttributeValues", "BlogImage"),
👍 I agree with @redreceipt here, we should follow the same logic we use to search a content item's attributes for images. 

While this code is in a separate task, you could potentially co-locate the code within the `Media` class to get access to all its helper methods. Look at how the `tags` tasks are arranged for examples.

2021-08-12 13:29 UTC, vinnyjth commented on dags/rock/rock_channel_image.py
> +        channelsWithImageValues = filter(lambda channel: channel, channelsWithImages)
💥 

can this be further simplified to `filter(channelsWithImages)`?

2021-08-12 13:29 UTC, vinnyjth commented on dags/rock/rock_channel_image.py
> +        if not self.kwargs["do_backfill"]:
Nice catch here!

2021-08-12 13:51 UTC, vinnyjth commented on dags/rock/rock_channel_image.py
> +        node_id = self.pg_hook.get_first(
Do you think we could move this inside the `if image_value` block so we don't make a postgres query if we don't have to?

2021-08-12 14:08 UTC, vinnyjth commented on dags/rock/rock_cover_image.py
> +        node_id = self.pg_hook.get_first(
Do you think we could combine this query, and the below query into a single query with a join? Would save on DB bandwidth :)

2021-08-12 14:09 UTC, vinnyjth commented on dags/rock/rock_cover_image.py
> +                self.update_content_item_cover_image(
💯

2021-08-12 14:10 UTC, tomthornton commented on dags/rock/rock_cover_image.py
> +        node_id = self.pg_hook.get_first(
Yep I was just trying to get it done yesterday. That's the query I reached out about. Do you mind writing it?

2021-08-12 14:17 UTC, vinnyjth commented
@redreceipt 
> this seems overkill to me, we just want the channel image to be the fallback content item image in the event there is no other. 

> we don't necessarily care about rock channels other than mapping them to categories. take my opinion with a grain of salt though, I don't know any DB schema arch strategies you guys have built thus far

The issue is that it's not a simple as "here's a url, it belongs on an image". We need to track that url on a media record, and that media record has to be attached to something. Otherwise we run into issues if that image ever changes, or if it's removed. 

That said, if you need to run this locally on River Valley to get those media files built out so you can move forward with the client, I full support that :) You could also "gasp" add those values by hand for now (assuming there's a limited number of areas that need those images)

2021-08-12 14:42 UTC, vinnyjth requested changes
Left a bit of feedback in the PR. Looking really good! Just a few places to cleanup

2021-08-16 13:52 UTC, vinnyjth requested changes
Hey @tomthornton! Looking really close, thanks for fixing the linter errors. I think we've bought ourselves enough time to get this right for all of the churches, (instead of just river valley) so we can take the time here to iron out some more details before we merge this 👍

2021-08-16 13:52 UTC, vinnyjth commented on dags/rivervalley-rock-content-item-dag.py
> +        channel_image.set_downstream(set_cover_image)
Logic here looks great! What do you think about using the bitwise operators here? Instead of set_downstream? I noticed that the astronomer docs advices against mixing and matching the two syntaxes 

https://www.astronomer.io/guides/managing-dependencies

2021-08-16 13:52 UTC, vinnyjth commented on dags/rock/rock_channel_image.py
> +        node_id = self.pg_hook.get_first(
@tomthornton Wanted to make sure you saw this comment :)

2021-08-16 13:52 UTC, vinnyjth commented on dags/rock/rock_channel_image.py
> +                lambda channel: safeget(channel, "AttributeValues", "BlogImage"),
@tomthornton I think we still need to think about this before merging, or make this PR specific to rivervalley.

2021-08-16 13:53 UTC, vinnyjth commented on dags/rock/rock_channel_image.py
> +                lambda channel: safeget(channel, "AttributeValues", "BlogImage"),
Looks like the PR review tool doesn't show context well - so I'll elaborate. We should use the same logic we use to determine what a cover image is on a content item to determine what the image is for a content channel :) looking for just the "BlogImage" attribute is too narrow and won't work for most churches.

2021-08-16 15:42 UTC, tomthornton commented
@vinnyjth made those changes :) this should make things run more smooth and consistent

2021-08-16 17:10 UTC, vinnyjth approved these changes

2021-08-16 17:18 UTC, merged