Import Rock Prayers to Postgres
ApollosProject/apollos-shovel pull request #62
Opened 2021-09-08 18:10 UTC by tomthornton

2021-09-09 15:04 UTC, vinnyjth requested changes
Hey @tomthornton - I haven't gotten a chance to review this in practice yet, but I left you some comments about the code after skimming it. I'll clone it down and give it a run a bit later. Thanks!

2021-09-09 15:04 UTC, vinnyjth commented on dags/rock/rock_prayer_requests.py
> +            UPDATE content_item
This should probably be `prayer_request`

2021-09-09 15:04 UTC, vinnyjth commented on dags/rock/rock_prayer_requests.py
> +            print(prayer_requests)
You'll probably want to remove this :)

2021-09-09 15:04 UTC, vinnyjth commented on dags/rock/rock_prayer_requests.py
> +                print("top: {top}")
I've spotted this in a few other places in the app (all my fault) ;) make sure you make these print statements formatted strings
```suggestion
                print(f"top: {top}")
```

2021-09-09 15:04 UTC, vinnyjth commented on dags/rock/rock_prayer_requests.py
> +            """ if not self.kwargs["do_backfill"]:
I asked this above, but I'll repeat it here. Any reason you're not setting up a `delta` dag?

2021-09-09 15:24 UTC, tomthornton commented on dags/core-rock-prayer-request-dag.py
> +
I was thinking that Prayers into Postgres would only be a one-time backfill. Do Prayers in Rock come from places other than an Apollos app?

2021-09-09 15:24 UTC, tomthornton commented on dags/rock/rock_prayer_requests.py
> +import nltk
Nope! I'll remove it.

2021-09-09 15:25 UTC, vinnyjth commented on dags/core-rock-prayer-request-dag.py
> +
They can (but normally don't). However right now moderation is only possible via Rock, so we'll need to keep whatever prayers we have in Rock updated in Postgres (and vice versa)

2021-09-09 15:26 UTC, tomthornton commented on dags/rock/rock_prayer_requests.py
> +                print("top: {top}")
👍

2021-09-09 15:27 UTC, tomthornton commented on dags/rock/rock_prayer_requests.py
> +            """ if not self.kwargs["do_backfill"]:
My reasoning was I thought since we're using strictly Postgres prayers we would only be migrating them over once

2021-09-09 15:29 UTC, vinnyjth commented on dags/rock/rock_prayer_requests.py
> +            """ if not self.kwargs["do_backfill"]:
Unfortunately no :/ We'll need to stay in sync with Rock until we have a mechanism to moderate without rock.

2021-09-09 15:39 UTC, tomthornton commented on dags/core-rock-prayer-request-dag.py
> +
Oh okay that makes sense.

2021-09-09 16:25 UTC, tomthornton commented on dags/rock/rock_prayer_request_dag.py
> +        prayer_requests
Yeah the linter doesn't like it. Do we just merge it anyways

2021-09-09 20:14 UTC, vinnyjth commented on dags/rock/rock_prayer_request_dag.py
> +        prayer_requests
Nah, you should be able to remove it with not difference in functionality.

2021-09-13 20:27 UTC, vinnyjth commented on dags/rock/rock_prayer_requests.py
> +            columns = (
@tomthornton just making sure you saw this :)

2021-09-14 13:11 UTC, tomthornton commented on dags/rock/rock_prayer_requests.py
> +            columns = (
@vinnyjth I actually didn't, thanks! I looked over this before but couldn't see any new comments. Looking into this now.

2021-09-14 14:56 UTC, tomthornton commented
@vinnyjth this should be ready :)

2021-09-14 15:13 UTC, vinnyjth commented
Thanks @tomthornton! Once you fix the linter errors I will take a look at it.

2021-09-14 18:41 UTC, tomthornton commented
@vinnyjth fixed the lint errors 👍

2021-09-16 17:01 UTC, tomthornton commented
@vinnyjth did we ever decide on what the fix for the lint error for `Klass` was?

2021-09-16 17:29 UTC, vinnyjth commented
> @vinnyjth did we ever decide on what the fix for the lint error for `Klass` was?

here is @redreceipt's recommendation which I support https://github.com/ApollosProject/apollos-shovel/pull/67#issuecomment-919423911

2021-09-16 17:51 UTC, tomthornton commented
Yep I agree. That works.

2021-09-17 16:30 UTC, tomthornton commented
@vinnyjth added the `approved` and `flag_count` fields from rock. Also updated the `created_at` time so that imported prayers from rock will always be when they were created, not when the dag runs.

2021-09-17 17:21 UTC, tomthornton commented
Also added the ability to delete prayer requests when deleted from rock. I figure we can extend this in the future to delete old/outdated prayer requests

2021-09-20 15:44 UTC, vinnyjth commented on dags/rock/rock_prayer_request_dag.py
> +    tags = [church, "prayer_request", "backfill"]
I'm not quite sure what your goal is with the names / tags variables here :)

2021-09-20 16:03 UTC, vinnyjth commented on dags/rock/rock_prayer_requests.py
> +            "SELECT origin_id, id FROM prayer_request"
I found a subtle bug, that _might_ not ever be a real issue in production - but we should probally protect against. 

When I ran the delete task I had a single prayer _not_ attached to a rock prayer in my DB. After the task ran, that prayer was gone (deleted). What do you think about not touching (deleting) prayers that didn't come from rock? that might be the case if the church ever detaches from rock but doesn't turn off the dag, or if the church has a bunch of prayers (not through rock) and then starts using the dag. I think we could exclude those prayers by adding `where origin_id is not null` to the query above.

2021-09-20 17:24 UTC, tomthornton commented on dags/rock/rock_prayer_requests.py
> +            "SELECT origin_id, id FROM prayer_request"
@vinnyjth yeah sure, I can add that!

2021-09-20 17:26 UTC, tomthornton commented on dags/rock/rock_prayer_request_dag.py
> +    tags = [church, "prayer_request", "backfill"]
I think it was just a bad copy and paste.

2021-09-20 18:11 UTC, vinnyjth approved these changes

2021-09-20 18:11 UTC, merged