feature: Delete Rock content item connections
ApollosProject/apollos-shovel pull request #71
Opened 2021-09-22 17:38 UTC by tomthornton

### About
Adds tests for content item connections and provides the ability to delete connections from Postgres if removed in Rock

### Testing

`pytest -k "content_item_connections" -s`
### Screenshots
 
<img width="991" alt="Screen Shot 2021-09-22 at 1 38 00 PM" src="https://user-images.githubusercontent.com/40962668/134393788-63abd916-da61-4902-9984-562e17aeda6d.png">

2021-09-22 19:24 UTC, tomthornton commented
@vinnyjth ah okay, that makes sense. Need to compare them by parent instead of all at once.

2021-09-22 20:55 UTC, tomthornton commented
@vinnyjth latest changes should fix the delta DAG. It matches up by parent id now instead of just plain connection origin id

2021-09-22 23:16 UTC, vinnyjth commented
Still seeing the same thing @tomthornton 

Delta DAG is deleting all the connections from my database every time. I think the current approach will always suffer from this issue? Do you think it's worth breaking off the `delete` code into a separate task and then fetching all items from rock and postgres there? 
![image](https://user-images.githubusercontent.com/1637694/134433879-eecf72c9-2347-4ceb-a32f-04ad4dfd7d2b.png)

![image](https://user-images.githubusercontent.com/1637694/134433904-211fd616-3f55-470e-adfe-19d8677740a1.png)

2021-09-23 14:48 UTC, tomthornton commented
@vinnyjth the problem was this line. Shouldn't have been removing them when they aren't part of the rock response. I removed it and the delta DAG is working now. 
````
else:
     for children_connection_id in children_connection_ids:
          deleted_content_item_connection_ids.append(children_connection_id)```

2021-09-23 16:28 UTC, vinnyjth commented on tests/cassettes/content_item_connections/delete_content_item_connection.yaml
> +    uri: https://rock.apollos.app/api/ContentChannelItemAssociations?%24top=10000&%24skip=0&%24select=Id%2CChildContentChannelItemId%2CContentChannelItemId%2COrder&%24orderby=ModifiedDateTime+desc
I think the reason the tests are passing is that these items wouldn't be returned from Rock if they were deleted. You get nothing back in the real world.

2021-09-23 17:31 UTC, tomthornton commented on tests/cassettes/content_item_connections/delete_content_item_connection.yaml
> +    uri: https://rock.apollos.app/api/ContentChannelItemAssociations?%24top=10000&%24skip=0&%24select=Id%2CChildContentChannelItemId%2CContentChannelItemId%2COrder&%24orderby=ModifiedDateTime+desc
You're right. It worked with one parent item but another when I tried it in Rock.

2021-09-23 17:37 UTC, tomthornton commented
@vinnyjth the latest change should actually fix the problem. I think we are going to have to fetch every rock content item connection everytime the delta dag runs, to make sure that they are still there. The only issue I see (that's maybe not even an issue) is that every content item connection is upserted on each dag run. I don't believe this impacts performance?

Rewriting the test now. I'll need to include multiple parent items.

2021-09-23 17:54 UTC, vinnyjth commented
@tomthornton We have a pattern in other parts of the shovel of splitting `delete` operations into a seperate dag? What do you think about that? That way we can keep this task `fetch_and_save_content_items_connections` super sharp and focused, and let another task handle the slower operation of checking for deletions.

2021-09-23 18:00 UTC, tomthornton commented
@vinnyjth yeah I'm fine with that, it will just mean more requests to Rock.

2021-09-23 18:06 UTC, vinnyjth commented
@tomthornton That is totally fine in this case, since there are a few very quick requests made to rock in the original task and then we can leave the potentially slower larger requests for a different task.

2021-09-23 18:08 UTC, vinnyjth commented on dags/rock/rock_content_items_connections.py
> +        for id, children_connection_ids in postgres_parent_items.items():
Is this methodology (and the associated query) necessary? Is it doing anything differently than the code you had in an earlier commit?

2021-09-23 18:16 UTC, tomthornton commented on dags/rock/rock_content_items_connections.py
> +        for id, children_connection_ids in postgres_parent_items.items():
@vinnyjth no it's not doing anything different, but I did add the following so that if a parent item removes it's only child, then it will also be deleted.
```
else:
     for children_connection_id in children_connection_ids:
          deleted_content_item_connection_ids.append(children_connection_id)```

2021-09-23 18:19 UTC, vinnyjth commented on dags/rock/rock_content_items_connections.py
> +        for id, children_connection_ids in postgres_parent_items.items():
@tomthornton Do you think it's worth reverting to the earlier code since it's simpler and easier to follow

2021-09-23 18:50 UTC, vinnyjth commented
@tomthornton let me know when you're ready for me to review this :)

2021-09-23 19:30 UTC, tomthornton commented
@vinnyjth ready! simplified that deletion logic

2021-09-23 19:33 UTC, vinnyjth commented on dags/rock/rock_content_item_dag.py
> +        connections >> set_parent_id >> features >> delete_connections
Nice! you can probably have this run concurrently with `set_parent_id` though, is there a reason it needs to wait for `set_parent_id` or `features`?

2021-09-23 19:37 UTC, tomthornton commented
@vinnyjth weird I think it deleted your review?

2021-09-23 19:52 UTC, vinnyjth requested changes
Looking good! a few changes needed related to style and dead code / missing code.

2021-09-23 19:52 UTC, vinnyjth commented on dags/rock/rock_content_item_dag.py
> +        connections >> set_parent_id >> features >> delete_connections
Nice! you can probably have this run concurrently with set_parent_id though, is there a reason it needs to wait for set_parent_id or features?

2021-09-23 19:52 UTC, vinnyjth commented on dags/rock/rock_content_items_connections.py
> +        rock_parent_items = {}
Is this used anywhere?

2021-09-23 19:52 UTC, vinnyjth commented on dags/rock/rock_content_items_connections.py
> -            if not self.kwargs["do_backfill"]:
You probably don't mean to delete this.

2021-09-23 19:52 UTC, vinnyjth commented on dags/rock/rock_content_items_connections.py
> +            for content_item_connection in rock_objects:
Is this dead code?

2021-09-23 19:52 UTC, vinnyjth commented on dags/rock/rock_content_items_connections.py
> +                "$select": "Id,ChildContentChannelItemId,ContentChannelItemId,Order",
Do you need to fetch the `Order` attribute?

2021-09-23 19:52 UTC, vinnyjth commented on dags/rock/rock_content_items_connections.py
> +        print(rock_content_item_connection_ids)
Do you want to leave this `print` in for the final version of the code?

2021-09-23 19:52 UTC, vinnyjth commented on dags/rock/rock_content_items_connections.py
> +    Klass = (  # noqa N806
Let's set this task up the way @tomthornton recommended :) I can't remember what it is exactly, but it's involves moving the class instantiation inline. something like 

```
content_item_connection_task = ContentItemConnection(kwargs) if "klass" not in kwargs else kwargs["klass"](kwargs)
```

2021-09-23 19:52 UTC, vinnyjth commented on tests/test_rock_content_item_connections.py
> +def test_run_fetch_and_save_content_item_connections(monkeypatch):
Nice test! Very easy to follow.

2021-09-23 19:52 UTC, vinnyjth commented on dags/rock/rock_content_item_dag.py
> +        connections >> [delete_connections, set_parent_id] >> features
is this syntax valid?

2021-09-23 19:52 UTC, vinnyjth commented on dags/rock/rock_content_items_connections.py
> +        postgres_content_item_connection_ids = list(
Nice! I like how this turned out. Simple and easy to follow.

2021-09-23 19:52 UTC, vinnyjth commented on dags/rock/rock_content_items_connections.py
> +                "$select": "Id,ChildContentChannelItemId,ContentChannelItemId,Order",
On second thought, it's not a bad idea since we're paginating.

2021-09-23 19:52 UTC, vinnyjth commented on dags/rock/rock_content_items_connections.py
> +            print(rock_objects)
dead code?

2021-09-23 20:03 UTC, vinnyjth commented on dags/rock/rock_content_item_dag.py
> +        connections >> [delete_connections, set_parent_id] >> features
@tomthornton  ^

2021-09-23 20:05 UTC, vinnyjth commented on dags/rock/rock_content_item_dag.py
> +        connections >> [delete_connections, set_parent_id] >> features
Just tested - looks like it is. I thought I had run into issues with this syntax in the past. Apologies!

2021-09-23 20:13 UTC, vinnyjth commented on dags/rock/rock_content_items_connections.py
> +                "$select": "Id,ChildContentChannelItemId,ContentChannelItemId,Order",
Sorry @tomthornton  - I confused myself here :) My question 

> Do you need to fetch the Order attribute?

still stands. I had a seperate question about `$orderby` that I meant to leave my second comment about pagination on.

2021-09-23 20:16 UTC, vinnyjth approved these changes
Nice work Tom! Thanks for the great PR description to help get started reviewing.

2021-09-23 20:28 UTC, tomthornton commented
@vinnyjth Thanks! The templates were a good idea. Thanks for your help/input on this

2021-09-23 20:35 UTC, merged